### ISSUE TITLE
Support for dynamic URL

### ISSUE THREAD

**Issue by ajaleelp** [vivek12345/react-polling#3]
Thanks for the handy component @vivek12345 👍 
I was wondering if there is anyway to modify the url on each poll - say `/resource/1`, `/resource/2` etc. From what I could gather, this is not possible as of now?

**Comment by VivekNayyar** [comment]
Thank you @ajaleelp . You are right, as of now you can not change the url dynamically after a success or a failure case.
May I know more about your use case so that I can think towards implementing it?

**Comment by vivek12345** [comment]
Thanks @ajaleelp and yes you are right, as of now we do not support changing the url on a success or a failure event.

May I know more about your use case here so that I can think about implementing this if it's a use-case that everyone needs?

**Comment by ajaleelp** [comment]
I was trying to implement a _psuedo-live feed_ by polling for a resource with _id_ above the latest I have. Got it working with a `setInterval` and `fetch` combination for now. But yeah, I guess it would be a nice addition for your work.

**Comment by vivek12345** [comment]
@ajaleelp Would you like to give this a try. Implementing dynamic url behaviour.

**Comment by vivek12345** [comment]
Hey @ajaleelp, apologies for the delay. The last couple of months have been really hectic in terms of work.
But I am hoping latest release v1.0.7 will address all your concerns.
Thank you for creating this issue and I hope the new release is helpful.

Please try it and let me know if it fixes your issue.

Here is the sandbox link which will demonstrate an example which is similar to your requirements

https://codesandbox.io/s/react-polling-custom-promise-dynamic-url-3z7h2?file=/src/App.js

**Comment by ajaleelp** [comment]
@vivek12345 Thank you for taking the time and getting this done 🙂 Unfortunately, it's been a while since I touched the project where I was using this. Will let you know if I ever get back to it. Cheers!
