### ISSUE TITLE
Do startPolling and stopPolling accept custom implementation as well?

### ISSUE THREAD

**Issue by anumit02kaur** [vivek12345/react-polling#33]
I'm not a 100% sure on the usage of startPolling and stopPolling. When will I need this? Can you pls provide an example for the same?

**Comment by vivek12345** [comment]
Hey @anumit02kaur thank you for your question. 
Here is a sample codesandbox where I am using start and stop polling
https://codesandbox.io/s/react-polling-basic-usage-zie3j?file=/src/App.js

Let me know if you need more clarity on this

**Comment by anumit02kaur** [comment]
Got it, thanks!
